### PR TITLE
Add support for stage-1 nullish coalescing operator

### PR DESCRIPTION
**Pull request by lehni**
See https://github.com/michaelgmcd/vscode-language-babel/issues/27

### CODE REVIEW

**Comment by michaelgmcd** [comment]
Looks great! Thanks.

**Comment by lehni** [comment]
Thanks for merging so quickly! Could you release a new version with this added?

**Comment by michaelgmcd** [comment]
Will do this later today 👍

**Comment by michaelgmcd** [comment]
Released in version 0.0.15

**Pull request merged**
